version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development
      - RESEND_API_KEY=${RESEND_API_KEY}
    command: npm run start-watch